version: '2'
services:
  backend:
    build:
      context: .
      dockerfile: df.dev
    image: deb:dev
    container_name: dev.backend
    environment:
      NODE_ENV: "development"
    volumes:
      - ".:/home/deb"
      - "/home/deb/node_modules"
    ports:
      - "3100:3000"
      - "5858:5858"
    entrypoint: ["npm", "run", "debug"]
